// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5HxwfhwHpGQpq3UiNMymN7yVHKp2Qjw',
    appId: '1:959302419607:web:82e3c2ca480123eee815d2',
    messagingSenderId: '959302419607',
    projectId: 'katholiks-9152a',
    authDomain: 'katholiks-9152a.firebaseapp.com',
    storageBucket: 'katholiks-9152a.firebasestorage.app',
    measurementId: 'G-DG83BE4N9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiqPCHY9heDnAMaCWQ2QT4Je4-pBKdttU',
    appId: '1:959302419607:android:40563399dead7b92e815d2',
    messagingSenderId: '959302419607',
    projectId: 'katholiks-9152a',
    storageBucket: 'katholiks-9152a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvH6s5LdhzVv8Z2GqxVYXXMP4-_PjbciE',
    appId: '1:959302419607:ios:afd2ad9fa6b095a5e815d2',
    messagingSenderId: '959302419607',
    projectId: 'katholiks-9152a',
    storageBucket: 'katholiks-9152a.firebasestorage.app',
    iosBundleId: 'com.example.katholiks',
  );
}
